services:
  web:
    build: ./app
    container_name: beerandrevolution_web_dev
    command: >
      bash -c "
      python manage.py migrate &&
      python manage.py fetch_amp_servers && python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8001 --reload
      "
    env_file: .env
    volumes:
      - ./app:/app
      - ./app/staticfiles:/app/staticfiles
      - ./app/media:/app/media
    networks:
      - beerandrevolution_network
    restart: unless-stopped
    ports:
      - "8001:8001"

  bot:
    build: ./bot
    container_name: beerandrevolution_bot
    env_file: .env
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=config.settings
    volumes:
      - ./app:/app:ro
    depends_on:
      - web
    networks:
      - beerandrevolution_network
    restart: unless-stopped

networks:
  beerandrevolution_network:
    driver: bridge
